name: First_Workflow_with_multiple_bash
on: workflow_dispatch
jobs:
  First_job_a: My job_a
  runs-on: ubuntu-latest
    steps:
      - name: Prin-greeting 
        run: echo "Hello World"
      - name: Print output 
        run: echo "Hello blue"
     
  
  
    
